version: '2'

volumes:
  website-data: {}

services:
  # Reverse proxy
  nginx:
    build: nginx/
    ports:
      - '80:80'
    restart: always

  # website
  website:
    extends:
      file: common-services.yml
      service: website-base
    command: /bin/bash -lc 'rm -f tmp/pids/server.pid; rails s -p 4000'
    ports:
      - '4000:4000'

  website-db:
    build: website-db/
    volumes:
      - 'website-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: website
      POSTGRES_PASSWORD: website_pass
